config/routes.rb
Rails.application.routes.draw do
 root to: 'tops#start'

  resources :books
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
   @book = Book.new(book_params)
   @books = Book.all
  if @book.save
    flash[:notice] = "Book was successfully created."
   redirect_to book_path(@book.id)
  else
   render :index

  end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
     flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book.id)
   else
      render :edit
   end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

private
def book_params
  params.require(:book).permit(:title, :body)
end


end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def start
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>
 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
 <ul>
   <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
   <% end %>

 </ul>
<% end %>



<%= form_with model: @book do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>
<div>

<%= f.submit 'Update Book' %>
</div>

<%= link_to "Show", book_path(@book.id) %>
|
<%= link_to "Back", books_path %>

<% end %>

app/views/books/index.html.erb
<h1  class= "head">Books</h1>
  <table>
   <tr>
      <th>Title</th>
      <th>Body</th>
      <th> </th>
    </tr>
  <% @books.each do |book| %>
  <div class= "main">

    <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td>
      <%= link_to "Show", book_path(book.id) %>
      <%= link_to "Edit", edit_book_path(book.id) %>
      <%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
    <td>
    </tr>
  </div>
  <% end %>
</table>

<div class= "new-book">
  <h1>New book</h1>
  <% if @book.errors.any? %>
　<%= @book.errors.count %>errors prohibited this book from being saved:
　<ul>
　  <% @book.errors.full_messages.each do |message|%>
　  <li><%= message %></li>
　  <% end %>

　</ul>
　<% end %>
<%= form_with model: @book do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>
<% end %>

</div>

app/views/books/show.html.erb
<div class= "show">
  <div class= "flash-text">
    <%= flash[:notice] %>
  </div>
  <div class= "edit-title">
    <h4 class= "edit-text">Title:</h4>
    <p class= "edit-text"><%= @book.title %></p>
  </div>

 <div class= "edit-body">
    <h4 class= "edit-text">Body:</h4>
    <p class= "edit-text"><%= @book.body %></p>
 </div>

<%= link_to "Edit", edit_book_path(@book.id) %>
|
<%= link_to "Back", books_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tops/start.html.erb
<h1 class= "welcom-title">ようこそ　Bookers　へ！</h1>
<div class= "welcom-text">
<p>
    Bookersでは、さまざまな書籍に関するあなたの意見や<br/>
    印象を共有し交換することができます
</p>
</div>

<div class= "start"><%= link_to "start", books_path %></div>